name: Deploy to Google Cloud
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - index.ts
      - Pulumi.dev.yaml

jobs:
  deploy:
    uses: ./.github/workflows/pulumi.yml
    with:
      pulumi-subcommand: up
    secrets: inherit
