name: Pulumi Setup
on:
  workflow_call:
    inputs:
      pulumi-subcommand:
        required: true
        type: string
        description: "Pulumi subcommand to run"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Google Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker asia-southeast1-docker.pkg.dev --quiet
      - name: Fix cache permissions
        if: inputs.pulumi-subcommand == 'up'
        run: |
          sudo chown -R $USER:$USER /var/lib/docker
          sudo chmod -R 777 /var/lib/docker
      - name: Cache Docker layers
        if: inputs.pulumi-subcommand == 'up'
        uses: actions/cache@v3
        with:
          path: /var/lib/docker
          key: docker-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            docker-${{ runner.os }}-
      - name: Deploy to GCP
        uses: pulumi/actions@v6
        env:
          PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
        with:
          command: ${{ inputs.pulumi-subcommand }}
          cloud-url: gs://my-pulumi-state-bucket
          stack-name: dev
