name: Teardown
on:
  workflow_dispatch:
    inputs:
      remove-stack:
        description: "Delete project (remove stack) (optional) (WARNING: this action is irreversible, you have been warned)"
        required: true
        type: boolean
        default: false

jobs:
  teardown:
    uses: ./.github/workflows/pulumi.yml
    with:
      pulumi-subcommand: destroy
    secrets: inherit
  remove-stack:
    needs: teardown
    if: github.event.inputs.remove-stack == 'true'
    uses: ./.github/workflows/pulumi.yml
    with:
      pulumi-subcommand: stack rm dev
    secrets: inherit
