name: Teardown
on:
  workflow_dispatch:
    inputs:
      test:
        description: "Hello there"
        required: true
        type: boolean
        default: false

jobs:
  teardown:
    uses: ./.github/workflows/pulumi.yml
    with:
      pulumi-subcommand: destroy
    secrets: inherit